# Docker Compose for Edge Hub (Raspberry Pi)
version: '3.8'

services:
  # Edge Hub Application
  edge-hub:
    build:
      context: ./apps/edge-hub
      dockerfile: Dockerfile.arm64
    environment:
      - NODE_ENV=production
      - DB_PATH=/data/edge-hub.db
      - MQTT_BROKER_URL=mqtt://localhost:1883
      - CLOUD_SYNC_ENDPOINT=${CLOUD_API_URL}
      - CLOUD_API_KEY=${CLOUD_API_KEY}
      - LOG_LEVEL=info
    volumes:
      - edge_data:/data
      - /dev:/dev
      - /sys:/sys
    ports:
      - "3000:3000"
    networks:
      - edge-network
    restart: unless-stopped
    privileged: true  # For hardware access
    devices:
      - /dev/i2c-1:/dev/i2c-1  # I2C access
      - /dev/spidev0.0:/dev/spidev0.0  # SPI access
      - /dev/ttyUSB0:/dev/ttyUSB0  # Serial access (if available)

  # Local MQTT Broker
  mosquitto-edge:
    image: eclipse-mosquitto:2.0
    volumes:
      - ./config/mosquitto-edge.conf:/mosquitto/config/mosquitto.conf
      - mosquitto_edge_data:/mosquitto/data
    ports:
      - "1883:1883"
    networks:
      - edge-network
    restart: unless-stopped

  # Local PWA Server
  pwa-farmer:
    build:
      context: ./apps/pwa-farmer
      dockerfile: Dockerfile
    environment:
      - REACT_APP_EDGE_HUB_URL=http://localhost:3000
      - REACT_APP_MQTT_URL=ws://localhost:1883
    volumes:
      - pwa_cache:/usr/share/nginx/html/cache
    ports:
      - "3001:80"
    networks:
      - edge-network
    restart: unless-stopped

  # System Monitoring
  node-exporter:
    image: prom/node-exporter:latest
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - "9100:9100"
    networks:
      - edge-network
    restart: unless-stopped

  # Local Time Series Database (Optional)
  influxdb:
    image: influxdb:2.7-alpine
    environment:
      - INFLUXDB_DB=soilwise
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
    volumes:
      - influxdb_data:/var/lib/influxdb2
    ports:
      - "8086:8086"
    networks:
      - edge-network
    restart: unless-stopped

networks:
  edge-network:
    driver: bridge

volumes:
  edge_data:
  mosquitto_edge_data:
  pwa_cache:
  influxdb_data:
